# Generated by Django 4.2.5 on 2023-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='remaining_incorrect_guesses',
            field=models.IntegerField(default=0),
        ),
    ]
